name: Test public template bot usage

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches:
  #     - "main"
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 2 * * *' # every day at 2:00 AM

jobs:
  template-bot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Copy template pyproject.toml
        run: cp .github/scripts/pyproject.public-template-bot.toml pyproject.toml
      - name: Generate lock file
        run: poetry lock
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run template bot test
        run: poetry run pytest .github/scripts/test_public_template_bot.py
        env:
          METACULUS_TOKEN: ${{ secrets.METAC_GPT_4O_TOKEN }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
