name: Market Pulse Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *" # runs at midnight every 3 days

# Add concurrency group to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

# Daily job to run the forecast bot
jobs:
  bot_gpt4o:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GPT_4O_TOKEN+market-pulse-25q3'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT_4O_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o3_token:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O3_TOKEN+market-pulse-25q3'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O3_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_deepseek_r1:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_TOKEN+market-pulse-25q3'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_TOKEN }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
